export const shopActionTypes = {
  UPDATE_COLLECTION_START: 'UPDATE_COLLECTION_START',
  UPDATE_COLLECTION_SUCCESS: 'UPDATE_COLLECTION_SUCCESS',
  UPDATE_COLLECTION_FAILURE: 'UPDATE_COLLECTION_FAILURE',
}

