export const CartTypes = {
  TOGGLECARTDROPDOWNHIDDEN: 'TOGGLECARTDROPDOWNHIDDEN',
  ADDITEM: 'ADD_ITEM',
  CLEAT_ITEM_FROM_CART: 'CLEAT_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  REMOVEITEM: 'REMOVE_ITEM'
}
