export const UserActionTypes = {
  GOOLE_SIGNIN_START: 'GOOLE_SIGNIN_START',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  SIGNIN_SUCCESS: 'EMAIL_SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'GOOLE_SIGNIN_FAILURE',
}